version: 2
base_image: &base_image
  image: circleci/node:8.9.4

jobs:
  npm_install:
    docker:
      - <<: *base_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package.json" }}
            - npm-{{ .Branch }}-
            - npm-master-
      - run: npm install
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - <<: *base_image
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  test:
    jobs:
      - npm_install
      - test:
          requires:
            - npm_install
